"""
mdflow.generators.markdown — generate a Markdown analysis report.
"""
from __future__ import annotations
from ..models import MdDocument


def generate_markdown_report(
    doc: MdDocument,
    structure_analyzer,
    code_analyzer,
    toon_analyzer,
) -> str:
    sections = structure_analyzer.section_summary(doc)
    inventory = code_analyzer.inventory(doc)
    metrics = toon_analyzer.metrics(doc)

    lines: list[str] = []

    lines += [
        f"# mdflow report · {doc.title}",
        "",
        f"**File:** `{doc.path}`  ",
        f"**Headings:** {len(doc.headings)}  **Code blocks:** {inventory['total']}  "
        f"**Links:** {len(doc.links)}  **Markpact refs:** {len(inventory['markpact_paths'])}",
        "",
    ]

    # Metadata
    if doc.metadata:
        lines += ["## Metadata", ""]
        lines += [f"| Key | Value |", "| --- | --- |"]
        for k, v in doc.metadata.items():
            lines.append(f"| `{k}` | `{v}` |")
        lines.append("")

    # Health / TOON
    if metrics["health"]:
        lines += ["## Health Metrics", ""]
        for k, v in metrics["health"].items():
            lines.append(f"- **{k}**: `{v}`")
        lines.append("")

    if metrics["alerts"]:
        lines += ["## Alerts", ""]
        for a in metrics["alerts"]:
            lines.append(f"- ⚠ {a}")
        lines.append("")

    if metrics["refactors"]:
        lines += ["## Refactor Recommendations", ""]
        for r in metrics["refactors"]:
            lines.append(f"- 🔧 {r}")
        lines.append("")

    # Document structure
    lines += ["## Section Overview", ""]
    lines += ["| Section | Level | Code blocks | Languages | Links |", "| --- | --- | --- | --- | --- |"]
    for s in sections:
        langs = ", ".join(f"`{l}`" for l in s["languages"]) or "—"
        mps = ", ".join(f"`markpact:{m}`" for m in s["markpact"]) if s["markpact"] else ""
        label = f"[{s['heading']}](#{s['anchor']}){' ' + mps if mps else ''}"
        lines.append(f"| {label} | H{s['level']} | {s['code_blocks']} | {langs} | {s['links']} |")
    lines.append("")

    # Code inventory
    if inventory["by_language"]:
        lines += ["## Code Block Inventory", ""]
        lines += ["| Language | Blocks | Markpact |", "| --- | --- | --- |"]
        for lang, items in inventory["by_language"].items():
            mp = sum(1 for i in items if i["markpact"])
            lines.append(f"| `{lang}` | {len(items)} | {mp} |")
        lines.append("")

    # Markpact refs
    if inventory["markpact_paths"]:
        lines += ["## Embedded File References (markpact)", ""]
        for p in inventory["markpact_paths"]:
            lines.append(f"- `{p}`")
        lines.append("")

    # Mermaid diagrams inline
    lines += [
        "## Diagrams",
        "",
        "### Section Flow",
        "",
        "```mermaid",
    ]
    # Inline simple section flow
    lines += [f"flowchart TD"]
    prev = None
    for i, s in enumerate(sections[:15]):
        nid = f"S{i}"
        lines.append(f'  {nid}["{s["heading"]}"]')
        if prev is not None:
            lines.append(f"  S{prev} --> {nid}")
        prev = i
    lines += ["```", ""]

    # Links
    if doc.links:
        lines += ["## Links", ""]
        lines += ["| Line | Kind | URL | Text |", "| --- | --- | --- | --- |"]
        for lk in doc.links[:30]:
            lines.append(f"| {lk.line} | `{lk.kind}` | `{lk.href[:60]}` | {lk.text[:40]} |")
        lines.append("")

    lines += ["---", "_Generated by **mdflow** — Markdown dependency analyzer_"]

    return "\n".join(lines)
